
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            const theme = localStorage.getItem("admin_theme");
            document.documentElement.setAttribute("data-theme", theme);
          `,
          }}
        />
      </head>
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
